### ISSUE TITLE
FEATURE Request - Folders

### ISSUE THREAD

**Issue by Ghr00t** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#134]
Love this mod.  Would like to have a way of organizing all my lora models, etc.  Folder structure would be perfect.  Not sure if possible, just wanted to put it out there.  Cheers.

**Comment by midcoastal** [comment]
Further, I will be submitting a PR with two little things that should allow for automatically organizing Models based on trigger criteria (is Celebrity, is NSFW, tagged with XYZ, etc).  Needs to be run manually, but does the trick.

Keep an ear out.

**Comment by songib** [comment]
> sd webui's extra network always support sub folders.
@butaixianran 
Do you mean this extension can read all subfolder from my model directory?
I currently had a problem with dl some info files and the image, with multiple subfolders I use symbolic links as well for all my model since my storage is kinda full atm. What I did now is put all the models outside the subfolder so the extension can read the files and put it back again in the subfolder.

**Comment by butaixianran** [comment]
Subfolder is always supported in SD webui

Also there is a fork you can ask for some new features.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
