### ISSUE TITLE
Refresh Civ Helper button is gone in latest webui version

### ISSUE THREAD

**Issue by williamkmlau** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#146]
## Describe Issue
Updated to latest webui version, the refresh helper button is gone

## Screenshot for UI issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/34730446/e8857c8b-ec03-4450-be88-1914a52b9d7e)

**Comment by butaixianran** [comment]
There is no such issue on my side with latest version of sd webui.

Read common issue part of this project's document to find out the reason.

If you can not find the reason, offering following information:

* There is a version number at the bottom of this extension's tab page. Offer it here.
* There is a commit hash code at the bottom of sd webui page's bottom, which is a URL. Offer the whole URL here.
* Press F12, go to console log tab, if there is any error msg there, offer it to here.

**Comment by chen135347542093** [comment]
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/104272971/af1ccce1-9503-4ec9-b5fd-5036043b4ca0)
在这个插件里，也没反应

**Comment by butaixianran** [comment]
> Cannot see the button either. Just installed the extension:
> Using Safari version 16.4 (18615.1.26.110.1), macOS 13.3.1 (a) (22E772610a).

The refresh icon "🔁" is a unicode symbol, not a picture. If your browser can not display the icon in "🔁", that means your Mac is using a bad font. 

Mac's default font is lack of a lot of unicode symbols. So, the button may be there but your Mac may display this icon as empty string.  

You can try to use a font which included all unicode symbols. On unicode websites, following fonts are often suggested in their css:  
Arial,Helvetica,sans-serif, monospace, "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji"

**Comment by honzajavorek** [comment]
@butaixianran That is probably not the case, because I can see the symbol here on GitHub, also I can see the symbol elsewhere in the web UI.

<details>
<summary><i>Click to see screenshot of my UI</i></summary>
<img width="875" alt="Screenshot 2023-05-16 at 16 09 03" src="https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/283441/bc67e008-dce5-4a7a-b565-f3ccaa49e0ec">
</details>

<details>
<summary><i>Click to see screenshot of your GitHub comment</i></summary>
<img width="930" alt="Screenshot 2023-05-16 at 16 09 36" src="https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/283441/d3c3ae79-05ad-48f8-ae69-a0fd0f5191b5">
</details>

I'm using the extension regardless, because it's useful even without the buttons! But it would be awesome if I could debug this somehow and get the buttons working. Is there anything I can do to find out what could be the issue? The HTML looks like this, if this is of any help:

<details>
<summary><i>Click to see screenshot of the DOM</i></summary>
<img width="775" alt="Screenshot 2023-05-16 at 16 12 24" src="https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/283441/8843ab90-6b5b-4357-a199-36f97c2cf5bd">
</details>

**Comment by butaixianran** [comment]
If you can see the refresh icon, then you should see that  "🔁" button after opening extra network model list by clicking "🎴".

This "🔁" button will be loaded if it can find "Refresh" button's id.
![Snipaste_2023-05-16_22-46-14](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/5558722/150e68e8-d776-4994-8778-f999686ec502)

Form your console log's screenshot, There is no error when finding this id, that means, "🔁" button should be already loaded but not displayed. 

If you are not offering the full console log, just the last few lines, you need to check the full console log from beginning for any error.

If you forgot to open extra network list, you can click "🎴" to open it.

If there is no error in your full console log and extra network list is opened, then you can try to use chrome browser to see if this  "🔁" button can be displayed.

**Comment by honzajavorek** [comment]
@butaixianran Thanks a lot for your reply. I haven't been around my setup for a while, so I only got to proceed with debugging today. Aaaand… It works. I have to apologize and I'll only be lucky if my case won't get to the [Claim Wall](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/blob/main/claim_wall.md) 🤦‍♂️ 

<img width="1358" alt="Screenshot 2023-05-23 at 22 40 23" src="https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/283441/861fa9fa-2bb3-4700-b193-d46468e04fdc">

I don't know why, but previously I've been looking for the button at the top of the UI, even though it makes no sense. When I open 🎴, the button is there, next to the Search, and the covers overlay with buttons works as intended.

I'll show myself out now…

![homer](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/283441/6867beff-be55-479a-a081-132360c34069)
