### ISSUE TITLE
Enhancement request: Lora Trigger words

### ISSUE THREAD

**Issue by simonmcnair** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#197]
It would be good to have the same menu for the Lora as you do for the textual inversion ? where you have the trigger words, prompt for image etc ?

Apologies if I have missed anything,  and I understand it may be hard to do, but most Lora's have trigger words and it's a pain to have to note them down separately.

If this is too hard it would be good to have a text box that contains all the text from the civitai page, reformatted perhaps ?

**Comment by plashomb** [comment]
Not sure if you're looking for the "Add Trigger Words" button for LoRAs, but if you are, it should already be there. Look for a little lightbulb icon at the bottom of the preview image. If you don't see buttons, make sure to hit the blue refresh button so that they display. This will only add trigger words that are listed on Civitai, however, and there isn't an option to add your own custom prompt list, as far as I'm aware. (That's a feature I'd love to see in future versions, since I often use a custom combination of the trigger words rather than what's listed on Civitai).  

If what you're hoping for is a new enhancement, you'll likely have to wait until Civitai Helper 2 (renamed ModelInfo Helper) as the developer is no longer adding improvements to v1.x and are focused on developing v2.x.

**Comment by simonmcnair** [comment]
Ahhhh, you have to hover over the words for it to appear.  It would be nice to get the preview image, for the textual inversions too, if that is in the works :-)

**Comment by simonmcnair** [comment]
I don't understand it.  Sometimes this works, and sometimes it does not.  I'm moving the cursor over the text but it no longer appears in textual inversion or Lora.  I can't see anything in chrome when I inspect the window

**Comment by simonmcnair** [comment]
It seems as if it is showing replace preview instead of update_card_for_civitai

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
