### ISSUE TITLE
always_display config seems to be ignored in thumbnail mode

### ISSUE THREAD

**Issue by almagest21** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#51]
Thank you for brilliant extension. 
In thumbnail mode, the buttons always appear and the false of always_display config seems to be ignored. Could you please confirm this?
![issue](https://user-images.githubusercontent.com/95058689/225307725-4d0e3aaa-35c7-4a70-b790-fad77dbec80c.gif)

**Comment by butaixianran** [comment]
Yes, document is already explained that. Due to an issue of SD webui's css, under thumbnail mode, they can only always display, or don't display at all.  

In latest version of SD webui, I submit a quick fix for that and AUTOMATIC1111 merged it.  But I don't think most people gonna update their SD just for this quick fix. So, I won't fix it for now.   

This will be fixed in version 2.0, which gonna ask users to update their SD webui.
