### ISSUE TITLE
Issues with system junctions

### ISSUE THREAD

**Issue by alfonslm** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#71]
## Have you read document?
Yes

## Have you checked console log window's msg?
Yes

## Describe Issue
My guess is that the script don't work with system links that I use to save HDD/SSD space since I have two versions of SD installed for plugin compatibility.

## Screenshot
![image](https://user-images.githubusercontent.com/10770782/227717838-d78489f1-ca19-4618-8668-9d8466491dcd.png)

## Console log's msg or screenshot for function issue
Civitai Helper: Start scan_model
Civitai Helper: Scanning path: E:\StableDiffusion\stable-diffusion-webui-krita\embeddings
Civitai Helper: Checking preview image for model: E:\StableDiffusion\stable-diffusion-webui-krita\embeddings\micromini.pt
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\StableDiffusion\stable-diffusion-webui-krita\embeddings\microskirt.pt
Civitai Helper: Model Info is empty
Civitai Helper: Scanning path: E:\StableDiffusion\stable-diffusion-webui-krita\models\hypernetworks
Civitai Helper: Scanning path: E:\StableDiffusion\stable-diffusion-webui-krita\models\Stable-diffusion
Civitai Helper: Creating model info for: artErosAerosATribute_aerosINPAINTINGNovae-inpainting.safetensors
Civitai Helper: Use Memory Optimized SHA256
Traceback (most recent call last):
  File "E:\StableDiffusion\stable-diffusion-webui-krita\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\StableDiffusion\stable-diffusion-webui-krita\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "E:\StableDiffusion\stable-diffusion-webui-krita\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\StableDiffusion\stable-diffusion-webui-krita\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\StableDiffusion\stable-diffusion-webui-krita\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\StableDiffusion\stable-diffusion-webui-krita\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\StableDiffusion\stable-diffusion-webui-krita\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\lib\model_action_civitai.py", line 58, in scan_model
    hash = util.gen_file_sha256(item)
  File "E:\StableDiffusion\stable-diffusion-webui-krita\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\lib\util.py", line 32, in gen_file_sha256
    with open(filname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\StableDiffusion\\stable-diffusion-webui-krita\\models\\Stable-diffusion\\artErosAerosATribute_aerosINPAINTINGNovae-inpainting.safetensors'

**Comment by butaixianran** [comment]
Since you are using windows, "symbolic link" with mklink command is already supported. There is no reason to support another type of those links.

Also, SD webui has command line can set custom model folder, and this extension supports that too. There is no reason to use symbolic link or junction at all. 

For example, for checkpoint model, you can use custom folder like this: `--ckpt-dir Your/custom/model/folder`.
For lora, use: `--lora-dir`.

Check official wiki for other command:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings.

**Comment by alfonslm** [comment]
I'm using it to have two folders. One for my commonly used ckpt on my SSD and one for the less used ones on my HDD. Just setting a different folder don't help. But at least the plugin should not stop with an error in that way when the folder exists.

I guess that I should write a feature request to add multiple folder support.

**Comment by butaixianran** [comment]
does this file from error msg exist?

"E:\StableDiffusion\stable-diffusion-webui-krita\models\Stable-diffusion\artErosAerosATribute_aerosINPAINTINGNovae-inpainting.safetensors"

what is this file's real path?

Also, even you are using multiple folders for same model type, like I mentioned, Symbolic link with mklink command is already supported.

**Comment by alfonslm** [comment]
The file exists and since it was the first file in the folder the error stopped the check for all other files in the folder which is the real issue. I guess that one option could be to check all files in the folder and ignore the ones that cause issues.

The real path is "E:\StableDiffusion\Models\artErosAerosATribute_aerosINPAINTINGNovae-inpainting.safetensors"

The reason why it's set up that way is that I have two SD versions. One for a Krita API and one up to date.

**Comment by butaixianran** [comment]
I already explained, Symbolic link with mklink command is already supported. 

Why can't you use Symbolic link? It basically do the samething as junction and can be easily supported in python.

**Comment by alfonslm** [comment]
I use a GUI plugin to not have to use the CLI every time I move something, but I will guess that it doesn't work across drives for files with HardLinks. If you check the file, it is a .symlink

**Comment by alfonslm** [comment]
I might have fixed it, but I will still say that the stop on error in this case is a bug not a feature since it at least in this case should be able to continue.
If I forgot to say it, it's the "Scan Models for Civitai" Scan that I was talking about and "Get Model Info from Civitai by URL" it seems like it mostly worked.

**Comment by butaixianran** [comment]
You don't have to use cli everytime. Symbolic link onces created will be there forever, like a folder. 

Symbolic link do the same thing as junction, so no matter what you want to do with junction, symbolic link can do it, and can do it better. There is no reason to use junction at all. It causes a lot troubles. 

I'm also curious, do you use extra network in both of your SD webui? Because extra network does not handle junction too. If you can not use extra network, even this extension support junction, you still can not use this extension's scanning result. 

Every other guy who need multiple model folders, are using Symbolic link, not junction. Because junction is a trouble maker no one should use. If you still want to use that, we won't support it.

**Comment by butaixianran** [comment]
Added a quick fix for this error. Still, no full support for junction, may still can not find folder when downloading files.
